# Generated by Django 5.2.3 on 2025-07-01 10:49

import accounts.utils.image_upload
import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('admin', 'Admin')], help_text='Enter your account type...', max_length=20, null=True, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Enter your birth date...', null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='Enter your country', max_length=25, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Enter your gender...', max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload your image...', null=True, upload_to=accounts.utils.image_upload.USER_DIRECTORY_PATH, validators=[core.utils.VALIDATE_IMAGE_EXTENSION, core.utils.VALIDATE_IMAGE_SIZE], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, db_index=True, help_text='Enter your number...', max_length=20, null=True, unique=True, validators=[core.utils.VALIDATE_PHONE_NUMBER, django.core.validators.MinLengthValidator(5)], verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('admin', 'Admin')], help_text='Enter your role...', max_length=20, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, help_text='Enter your signature...', max_length=40, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Signature'),
        ),
    ]
